# Generated by Django 2.2.7 on 2019-11-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customers')),
            ],
        ),
    ]
