# Generated by Django 2.2.7 on 2019-11-21 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='checkingAcct',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('vendor_name', models.CharField(max_length=50)),
                ('transaction_date', models.DateField(null=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customers')),
            ],
        ),
    ]
