# Generated by Django 2.2.7 on 2019-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191121_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingacct',
            name='type_category',
            field=models.CharField(default='unknown', max_length=100, null=True),
        ),
    ]
