# Generated by Django 2.2.7 on 2019-11-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_checkingacct_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
