# Generated by Django 2.2.7 on 2019-11-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191121_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
