# Generated by Django 2.2.7 on 2019-11-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customers_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customers_List'),
        ),
    ]
