# Generated by Django 2.2.7 on 2019-11-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191122_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingacct',
            name='transaction_type',
            field=models.CharField(default='debit', max_length=100, null=True),
        ),
    ]
